config/routes.rb
Rails.application.routes.draw do
  get 'mixtapes/new'
  get 'session/new'
  # get 'pages/home'
  root :to => 'pages#home'
  resources :users, :only => [:new, :create, :index]

  # HTTP verbs
  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destory'

  resources :mixtapes, :only => [:new, :create, :show, :edit]
end

app/models/album.rb
class Album < ApplicationRecord
  has_many :songs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs
  has_many :genres, :through => :songs
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_and_belongs_to_many :songs
end

app/models/mixtape.rb
class Mixtape < ApplicationRecord
  belongs_to :user, :optional => true
  has_and_belongs_to_many :songs
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :album, :optional => true
  belongs_to :artist, :optional => true
  has_and_belongs_to_many :genres # HABTM
  has_and_belongs_to_many :mixtapes
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, :presence => true, :uniqueness => true
  has_many :mixtapes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :fetch_user

  private
  def fetch_user
    @current_user = User.find_by :id => session[:user_id] if session[:user_id].present?
    session[:user_id] = nil unless @current_user.present?
  end

  def check_for_login
    redirect_to login_path unless @current_user.present?
  end

  def check_for_admin
    redirect_to root_path unless @current_user.present? && @current_user.admin?
  end
end

app/controllers/mixtapes_controller.rb
class MixtapesController < ApplicationController
  before_action :check_for_login
  
  def new
    @mixtape = Mixtape.new
  end

  def create
    # create the mixtape
    mixtape = Mixtape.create mixtape_params
    # raise :hell
    if params[:mixtape][:images].present?
      params[:mixtape][:images].each do |image|
        req = Cloudinary::Uploader.upload(image)
        mixtape.images << req["public_id"]
      end
    end
    # associate the mixtape with the current user
    @current_user.mixtapes << mixtape
    # redirect_to root_path
    redirect_to root_path
  end

  def show
    @mixtape = Mixtape.find params[:id]
  end

  def edit
    @mixtape = Mixtape.find params[:id]
  end

  private
  def mixtape_params
    params.require(:mixtape).permit(:title, :id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    user = User.find_by :email => params[:email]
    # if the user exists and the bycrypt(params[:password]) == password_Digest
    if user.present? && user.authenticate(params[:password])
      # save the user in the session
      session[:user_id] = user.id
      redirect_to root_path
    # else
    else
      # invalid username or password
      # redisplay login
      # set error message
      flash[:error] = "Invalid username or password"
      redirect_to login_path # display error message here
    #end
    end
  end

  def destory
    session[:user_id] = nil
    redirect_to login_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_for_admin, :only => [:index]
  
  def index
    @users = User.all
  end
  
  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save 
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mixtapes_helper.rb
module MixtapesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tunr</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= cloudinary_js_config %>
  </head>

  <body>
    <nav>
      <%= link_to 'Home', root_path %> |
      <% if @current_user.present? %>
        <% if @current_user.admin? %>
          <%= link_to 'All Users', users_path %> | 
        <% end %>
        <%= link_to "New Mixtape", new_mixtape_path %> | 
        <%= link_to "Log Out #{ @current_user.email }", login_path, :method => 'delete' %>
      <% else %>
        <%= link_to 'Sign up', new_user_path %> | 
        <%= link_to 'Login', login_path %>
      <% end %>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/mixtapes/edit.html.erb
<h2>Edit Mixtape: <%= @mixtape.title %></h2>

<%= form_for @mixtape do |f| %>

  <%= f.label :title %>
  <%= f.text_field :title, :placeholder => 'Code James' %>
  
  <br>

  <%= f.submit %>

<% end %>

app/views/mixtapes/new.html.erb
<h1>New Mixtape</h1>

<%= form_for(@mixtape, :html => {:multipart => true}) do |f| %>

  <%= f.label :title %>
  <%= f.text_field :title, :placeholder => 'Code James' %>

  <%= f.label "Mixtape Image" %>
  <%= f.file_field :images, :multiple => true %>

  <%= f.submit %>

<% end %>

app/views/mixtapes/show.html.erb
<h2>Showing Mixtape: <%= @mixtape.title %></h2>

<% @mixtape.images.each do |image| %>
  <%= link_to cl_image_tag(image), root_path %>
<% end %>

app/views/pages/home.html.erb
<h1>Home Page</h1>
<p>Welcome to mixtapes</p>

<% if @current_user.present? %>
  <p>You are currently logged in as <%= @current_user.email %>, <%= @current_user.id %></p>

  <% @current_user.mixtapes.each do |m| %>
  
    <p><%= link_to m.title, mixtape_path(m.id) %></p>

  <% end %>
  
<% end %>

app/views/session/new.html.erb
<h1>Sign In</h1>

<% if flash[:error].present? %>
  <h2><%= flash[:error] %></h2>
<% end %>

<%= form_tag login_path do %>

  <%= label_tag :email %>
  <%= email_field_tag :email %>

  <%= label_tag :password %>
  <%= password_field_tag :password %>

  <%= submit_tag "Sign in" %>

<% end %>

app/views/users/index.html.erb
<h1>All Users</h1>

<% @users.each do |user| %>

  <p><%= user.email %></p>

<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<% if @user.errors.any? %>

  <ol>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ol>

<% end %>

<%= form_for @user do |f| %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "Sign up!" %>

<% end %>